apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
stringData:
  WORDPRESS_DB_HOST: postgres.bigdata.svc.cluster.local:5432
  WORDPRESS_DB_USER: hiveuser
  WORDPRESS_DB_PASSWORD: hivepassword
  WORDPRESS_DB_NAME: wordpress