version: "3.8"

services:

  # PostgreSQL Metastore
  postgres:
    image: postgres:15
    container_name: metastore-db
    environment:
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bigdata

  # Hadoop NameNode
  namenode:
    image: apache/hadoop:3
    container_name: namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    environment:
      HADOOP_HOME: /opt/hadoop
      CLUSTER_NAME: local
    env_file:
      - hadoop.env
    ports:
      - "9870:9870"   # HDFS Web UI
      - "9000:9000"   # HDFS
    volumes:
      - namenode_data:/tmp/hadoop-root/dfs/name
    networks:
      - bigdata

  # Hadoop DataNode
  datanode:
    image: apache/hadoop:3
    container_name: datanode
    hostname: datanode
    command: ["hdfs", "datanode"]
    env_file:
      - hadoop.env
    volumes:
      - datanode_data:/tmp/hadoop-root/dfs/data
    networks:
      - bigdata
    depends_on:
      - namenode

  # YARN ResourceManager
  resourcemanager:
    image: apache/hadoop:3
    container_name: resourcemanager
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    env_file:
      - hadoop.env
    ports:
      - "8088:8088"   # YARN Web UI
    networks:
      - bigdata
    depends_on:
      - namenode

  # YARN NodeManager
  nodemanager:
    image: apache/hadoop:3
    container_name: nodemanager
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - hadoop.env
    networks:
      - bigdata
    depends_on:
      - resourcemanager

  # Spark + Thrift Server + Jupyter
  spark:
    image: bitnami/spark
    container_name: spark
    hostname: spark
    environment:
      - SPARK_MODE=master
      - SPARK_EXTRA_CLASSPATH=/opt/bitnami/spark/jars/postgresql-42.7.1.jar
    ports:
      - "4040:4040"     # Spark UI
      - "8080:8080"     # Spark Master UI
      - "10001:10001"   # Thrift Server (Power BI)
      - "8888:8888"     # Jupyter
    volumes:
      - ./notebooks:/notebooks
      - ./data:/data
      - ./hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
      - ./start-spark.sh:/start-spark.sh
    command: bash /start-spark.sh
    networks:
      - bigdata
    depends_on:
      - postgres
      - namenode

volumes:
  postgres_data:
  namenode_data:
  datanode_data:

networks:
  bigdata:
    driver: bridge
