services:

  postgres:
    image: postgres:15
    container_name: metastore-db
    environment:
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bigdata

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=bigdata
    env_file:
      - hadoop.env
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode_data:/hadoop/dfs/name
      - hadoop_conf:/etc/hadoop
    networks:
      - bigdata

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    env_file:
      - hadoop.env
    volumes:
      - datanode_data:/hadoop/dfs/data
    networks:
      - bigdata
    depends_on:
      - namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    env_file:
      - hadoop.env
    ports:
      - "8088:8088"
    networks:
      - bigdata
    depends_on:
      - namenode

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    hostname: nodemanager
    env_file:
      - hadoop.env
    networks:
      - bigdata
    depends_on:
      - resourcemanager

  spark:
    image: apache/spark:3.5.8
    container_name: spark
    hostname: spark
    user: root
    environment:
      - HOME=/root
      - HADOOP_CONF_DIR=/etc/hadoop
      - YARN_CONF_DIR=/etc/hadoop
    ports:
      - "4040:4040"
      - "8080:8080"
      - "10001:10001"
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
      - ./data:/data
      - ./hive-site.xml:/opt/spark/conf/hive-site.xml
      - ./start-spark.sh:/start-spark.sh
      - hadoop_conf:/etc/hadoop
    command: bash /start-spark.sh
    networks:
      - bigdata
    depends_on:
      - postgres
      - namenode
      - resourcemanager

volumes:
  postgres_data:
  namenode_data:
  datanode_data:
  hadoop_conf:

networks:
  bigdata:
    driver: bridge