apiVersion: v1
kind: Service
metadata:
  name: spark
  namespace: bigdata
spec:
  selector:
    app: spark
  ports:
    - name: thrift
      port: 10001
      targetPort: 10001
    - name: jupyter
      port: 8888
      targetPort: 8888
    - name: ui
      port: 4040
      targetPort: 4040
  type: ClusterIP